services:
  front:
    build: ./php
    image: gwenefrei/cp-php:latest
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./php/www:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on: 
      - db
  
  db: 
    build: ./mysql
    image: gwenefrei/cp-mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-cp-data:/var/lib/mysql

volumes:
  mysql-cp-data: